### ISSUE TITLE
can't find *_out.dlg file

### ISSUE THREAD

**Issue by PeterEmmrich** [Valdes-Tresanco-MS/AMDock-win#10]
Hello! Really appreciate what you are doing, after spending far too many hours troubleshooting my way through running AutoDock&vina.

AutoDock vina runs fine for me and I am just going through the simple AutoDock4 docking procedure. Setting up the project, target and ligand, preparing input and automatic search space definition all work fine.

But when I try to run AutoDock, progress gets to about 10.0% (completing the grid maps successfully) before python just starts spitting out a neverending list of IO errors to do with not being able to find the .dlg output file:

AMDOCK: Traceback (most recent call last):
AMDOCK: File "C:\[PathToAMDock]\AMDock-win-master\lib\site-packages\AMDock\input_tab.py", line 2164, in autodock_output
AMDOCK:
AMDOCK: ADout = open(self.ADout_file)
AMDOCK: IOError
AMDOCK:  :
AMDOCK: [Ernno 2] No such file or directory: 'C:\\[PathToProject]\\results\\CoA_LsAAE3_5ie0_out.dlg'

That file is indeed missing, but a file 'CoA_LsAAE3_5ie0_01.dlg' is in that directory (with some contents).

That error message gets repeated over and over again until I cancel it and the run does not make any further progress.

This happens with various ligand files going in. 

Is this an error you have encountered before?
Cheers,
Peter

**Comment by Valdes-Tresanco-MS** [comment]
Hi Peter, thanks for reporting this issue. Can you detail the process you followed to be able to reproduce it?

**Comment by PeterEmmrich** [comment]
I am using Autodock4 with default settings.

I started by naming the project and selecting the working directory. Neither the working directory path nor the AMDock path have any spaces in them. Then I hit create project which finishes in an instant.

I selected a target .pdb file for the enzyme and a ligand .pdb and run the preparation (pH 7.4, no metals, simple docking), which completed in a few seconds.

Then I ran the automatic search space definition. This took a few minutes, but finished without error.

After that, when I start the Autodock4 run, it takes a few minutes to run Autogrid4 and then Prepare_dpf4 before it starts Autodock4 proper. It then immediately gets stuck, just repeating the same error message thousands of times until I kill it  (I don't know if it would eventually stop, but it does not make any progress beyond 10%).

The same input files work fine with Autodock Vina. I can share them with you if that would help?

Many thanks,
Peter

**Comment by Valdes-Tresanco-MS** [comment]
Yes, please, if you can send the files to me, it would be a great help. I will try to fix the error as soon as possible

**Comment by PeterEmmrich** [comment]
You can download them here: 
https://we.tl/t-rg2znu98e2

**Comment by Valdes-Tresanco-MS** [comment]
Hi Peter. The bug is definitely related to AMDock. I think at some point I forgot to optimize the automatic methodology with AD4. Right now I am in the process of submitting two articles for my PhD, but as soon as I have free time I will fix it. I hope AMDock continues to be useful to you.
Best regards!

**Comment by PeterEmmrich** [comment]
Hi Mario,
thanks for taking this on!
Do you know if there is some workaround I can use in the meantime? Don't
worry if not, I can probably make do with Autodock vina for the time being.
Cheers and good luck with your papers!
Peter

Am Mo., 3. Mai 2021 um 18:08 Uhr schrieb Mario Sergio Valdés Tresanco <
***@***.***>:

**Comment by PeterEmmrich** [comment]
Hi Mario,
just to let you know, I also had no luck with the 'Center on Residue' option - that always throws up a Division by Zero error. 

However, by getting the file up in pyMOL, selecting the residues of the active site and using the centerofmass command, I can get the coordinates of a good grid box center myself, so I can just enter them with the 'Box' option. I assume that is basically the same thing as the 'Center on Residue' option should be doing automatically. 

This works well as a workaround for me and runs much faster anyway.

Cheers,
Peter

**Comment by Valdes-Tresanco-MS** [comment]
In certain cases, this problem can occur. This is because the geometric center of the selected residue set is located within the structure and/or so AutoLigand fails to find a starting point ...
This is something we have to work on. For the new version, we will work with Dr. Michel Sanner to implement AutoSite which is more efficient.

Thank you very much for reporting the bug, I will try to fix it.

Best!
Mario S.

**Comment by Valdes-Tresanco-MS** [comment]
Hi Peter.
I've already worked on the bug. In my tests it works correctly. Can you confirm if it works correctly for you?
Best!
Mario S.

**Comment by PeterEmmrich** [comment]
Brilliant, yes that works now!

Though I might stick to setting the centre of the box by hand, now that I have figured out how to do that.

Thank you!
Peter

**Comment by Valdes-Tresanco-MS** [comment]
Excellent. 
In any case, if you have any difficulties, you can send me the files to review.

I forgot to mention it, but we fixed the automatic mode bug with AD4 and a bug related to locating the residue-centered search space

If the issue has already been resolved, please close it
Best!
Mario S.

**Comment by PeterEmmrich** [comment]
Awesome, thank you!
Best wishes,
Peter
