### ISSUE TITLE
run button is not working

### ISSUE THREAD

**Issue by hima111997** [Valdes-Tresanco-MS/AMDock-win#13]
I made all steps sequentially but when I click on the run button, nothing happens (no error messages are shown and the state does not change)
![image](https://user-images.githubusercontent.com/55895327/153630752-4c2fa6ff-6774-4446-868e-e83dcf415a43.png)

**Comment by Valdes-Tresanco-MS** [comment]
Why is your version 1.6.2 if we haven't updated it for windows?
I have to review, your example would help.

**Comment by hima111997** [comment]
i followed the commands on this link https://pypi.org/project/AMDock/
it said for linux but i could not find any commands to install on windows, so i tried it and it worked. i have windows 10

**Comment by Valdes-Tresanco-MS** [comment]
Currently, that PyPi version is for Linux and macOS only, since that version depends on other packages that need to be installed. For windows, just follow the instructions in the README for [AMDock-win](https://github.com/Valdes-Tresanco-MS/AMDock-win).

**Comment by hima111997** [comment]
okay thank you
