### ISSUE TITLE
Implement the use of the AD4 user-parameter file

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [Valdes-Tresanco-MS/AMDock-win#4]
-Add the option in the program settings.
-Autodetect the ligand atoms types.

**Comment by Mario0125** [comment]
Buenas tardes estoy utilizando AMDock --- (AutoDock4) para Windows.  Cuando quiero definir el tamaño de la caja, me cambia los valores y me deja el tamaño de 14x -14y -14z  cuando  le doy " Define Search Space". Gracias 

Adjunto evidencia 
![Captura](https://user-images.githubusercontent.com/64239144/86959872-3deac180-c124-11ea-8e2c-b236e73ec66d.JPG)

**Comment by Valdes-Tresanco-MS** [comment]
Oh, un error pequeño. Ya lo corregí.
Esté pendiente que pronto viene una versión superior de AMDock con nuevas funcionalidades y una mejor integración con PyMOL. Puedes ver el proyecto acá https://github.com/Valdes-Tresanco-MS/AMDock-win-py3.
Por favor déjame saber si se corrigió el problema.

**Comment by Mario0125** [comment]
Listo , ¿lo instalo de nuevo para comprobar  si se  corrigió el problema ?

**Comment by Valdes-Tresanco-MS** [comment]
Sí. De momento es la solución. En la nueva versión implementaré una opción de actualización automática.

**Comment by Mario0125** [comment]
Listo, Me funcionó , Gracias por contestar y por el tiempo. Saludos de Bucaramanga
![Cap](https://user-images.githubusercontent.com/64239144/86965016-8c03c300-c12c-11ea-9d28-04e34a718ec6.JPG)

**Comment by Valdes-Tresanco-MS** [comment]
A ti por usar el programa. 
Recuerda, la nueva versión vendrá cargada de novedades. 
Modificaré el Readme de este repositorio para anunciarla.
Saludos

**Comment by Mario0125** [comment]
Vale , estaré pendiente.
________________________________
De: Mario Sergio Valdés Tresanco <notifications@github.com>
Enviado: miércoles, 8 de julio de 2020 1:09 p. m.
Para: Valdes-Tresanco-MS/AMDock-win <AMDock-win@noreply.github.com>
Cc: MARIO ANDRES JURADO HERRERA <mario.jurado@ustabuca.edu.co>; Comment <comment@noreply.github.com>
Asunto: Re: [Valdes-Tresanco-MS/AMDock-win] Implement the use of the AD4 user-parameter file (#4)


A ti por usar el programa.
Recuerda, la nueva versión vendrá cargada de novedades.
Modificaré el Readme de este repositorio para anunciarla.
Saludos
